name: Build and Deploy 
on:
  push:
    branches: 
      - main
    paths:
      - mkdocs.yml
      - requirements.txt
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages  # The branch the action should deploy to. Has to be specified in the repo's settings.
          folder: .     # The folder the action should deploy from.
