name: Build and Deploy 
on:
  push:
    branches:
      - main
      #-main_techb0lt
    paths:
      - mkdocs.yml
      - requirements.txt
      - 'docs/'
      - 'includes/abbreviations.md'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Set up environment
        env:
          NCCDB_API_KEY: ${{ secrets.NCCDB_API_KEY }}
        run: |
          echo "NCCDB_API_KEY=$NCCDB_API_KEY" >> $GITHUB_ENV
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
